name: Reusable Deploy
on: workflow_call
jobs:
    reusable_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: echo "Deploying and uploading"