name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of deployable file name
                required: false
                default: dist
                type: string
jobs:
    reusable_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v4
              with: 
                name: ${{ inputs.artifact-name}}
            - name: Output Information
              run: echo "Deploying and uploading"   